language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - jruby-head
  - rbx-2
  - truffleruby
env:
  - INVOICE_EXPRESS_ACCOUNT_NAME=test-account-name INVOICE_EXPRESS_AKI_KEY=test-api-key
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx-2
    - rvm: truffleruby
  fast_finish: true
