bundler_args: --without development
language: ruby
before_install: gem install bundler -v '<2'
rvm:
  - 2.3
  - 2.4
  - 2.5.0
  - 2.6.3
  - jruby-head
  - rbx-2
gemfile:
  - Gemfile
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx-2
  fast_finish: true
